In [683]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv(r'C:\Users\leepa\Documents\color_mood_predictor_ml\data\color_dataset.csv')
df

R      G      B       H     S     L  Brightness  Target
0     110.0  185.0  219.0  198.72  0.60  0.65      166.45    Good
1     244.0   54.0  220.0  307.58  0.90  0.58      129.73  Medium
2     196.0  187.0   17.0   56.98  0.84  0.42      170.31  Medium
3     187.0    NaN  122.0     NaN   NaN   NaN         NaN     NaN
4      98.0  177.0    0.0   86.78  1.00  0.35      133.20  Medium
...     ...    ...    ...     ...   ...   ...         ...     ...
5495    9.0   81.0  228.0  220.27  0.92  0.46       76.23    Good
5496   71.0   65.0  228.0  242.21  0.75  0.57       85.38    Good
5497   24.0  162.0  184.0  188.25  0.77  0.41      123.25    Good
5498  181.0    NaN  191.0     NaN   NaN   NaN         NaN     NaN
5499   61.0   86.0   56.0  110.00  0.21  0.28       75.11  Medium

[5500 rows x 8 columns]

In [684]:
df.head(10)

R      G      B       H     S     L  Brightness  Target
0  110.0  185.0  219.0  198.72  0.60  0.65      166.45    Good
1  244.0   54.0  220.0  307.58  0.90  0.58      129.73  Medium
2  196.0  187.0   17.0   56.98  0.84  0.42      170.31  Medium
3  187.0    NaN  122.0     NaN   NaN   NaN         NaN     NaN
4   98.0  177.0    0.0   86.78  1.00  0.35      133.20  Medium
5   22.0  177.0   94.0  147.87  0.78  0.39      121.19  Medium
6  219.0  163.0   66.0   38.04  0.68  0.56      168.69  Medium
7   81.0  122.0   59.0   99.05  0.35  0.35      102.56  Medium
8    4.0  130.0  164.0  192.75  0.95  0.33       96.20  Medium
9   24.0  231.0   53.0  128.41  0.81  0.50      148.81  Medium

In [685]:
df.tail(10)

R      G      B       H     S     L  Brightness  Target
5490  106.0  218.0   99.0  116.47  0.62  0.62      170.95  Medium
5491  213.0   27.0  140.0  323.55  0.78  0.47       95.50  Medium
5492   13.0  144.0  254.0  207.39  0.99  0.52      117.37    Good
5493  127.0   13.0  185.0  279.77  0.87  0.39       66.69  Medium
5494  162.0    NaN  171.0     NaN   NaN   NaN         NaN     NaN
5495    9.0   81.0  228.0  220.27  0.92  0.46       76.23    Good
5496   71.0   65.0  228.0  242.21  0.75  0.57       85.38    Good
5497   24.0  162.0  184.0  188.25  0.77  0.41      123.25    Good
5498  181.0    NaN  191.0     NaN   NaN   NaN         NaN     NaN
5499   61.0   86.0   56.0  110.00  0.21  0.28       75.11  Medium

In [686]:
df.columns

Index(['R', 'G', 'B', 'H', 'S', 'L', 'Brightness', 'Target'], dtype='object')

In [687]:
df.size

44000

In [688]:
df.shape

(5500, 8)

In [689]:
df.dtypes

R             float64
G             float64
B             float64
H             float64
S             float64
L             float64
Brightness    float64
Target         object
dtype: object

In [690]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Medium    2607
Good      1376
Bad        744
Name: count, dtype: int64

In [691]:
#Checking for Null values
df.isna().sum()

R             275
G             273
B             278
H             773
S             773
L             773
Brightness    773
Target        773
dtype: int64

In [692]:
#There are missing values so we need to fill it with 
#Either mean mode or median based on the scenario.
#When to use them accordingly??????????

#Mean: sum of all values divided by number of total values
#Median: It is the middle value
#Mode()[0]: It is the value which appears most
#We are using Median to to fill to avoid overfitting or underfitting
#we will fill RGB with median and then HSL values are derived from this

In [693]:
df=pd.read_csv(r'C:\Users\leepa\Documents\color_mood_predictor_ml\data\color_dataset.csv')
for columns in ['R','G','B']:
    df[columns].fillna(df[columns].median(),inplace=True)

C:\Users\leepa\AppData\Local\Temp\ipykernel_11428\3878616181.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[columns].fillna(df[columns].median(),inplace=True)
C:\Users\leepa\AppData\Local\Temp\ipykernel_11428\3878616181.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

Fo

In [694]:
df

R      G      B       H     S     L  Brightness  Target
0     110.0  185.0  219.0  198.72  0.60  0.65      166.45    Good
1     244.0   54.0  220.0  307.58  0.90  0.58      129.73  Medium
2     196.0  187.0   17.0   56.98  0.84  0.42      170.31  Medium
3     187.0  129.0  122.0     NaN   NaN   NaN         NaN     NaN
4      98.0  177.0    0.0   86.78  1.00  0.35      133.20  Medium
...     ...    ...    ...     ...   ...   ...         ...     ...
5495    9.0   81.0  228.0  220.27  0.92  0.46       76.23    Good
5496   71.0   65.0  228.0  242.21  0.75  0.57       85.38    Good
5497   24.0  162.0  184.0  188.25  0.77  0.41      123.25    Good
5498  181.0  129.0  191.0     NaN   NaN   NaN         NaN     NaN
5499   61.0   86.0   56.0  110.00  0.21  0.28       75.11  Medium

[5500 rows x 8 columns]

In [695]:
df.isna().sum()

R               0
G               0
B               0
H             773
S             773
L             773
Brightness    773
Target        773
dtype: int64

In [696]:
#here we are implenting a function for the hsl values
import colorsys 
def rgb_to_hsl(R,G,B):
    r,g,b=R/255,G/255,B/255
    h,l,s=colorsys.rgb_to_hls(r,g,b)
    return round(h*360,2),round(s,2),round (l,2)


In [697]:
#APPLY THE FUNCTION ROW WISE
df['H'],df['S'],df['L']=zip(*df.apply(lambda row: rgb_to_hsl(row['R'],row["G"],row["B"]),axis=1))
df

R      G      B       H     S     L  Brightness  Target
0     110.0  185.0  219.0  198.72  0.60  0.65      166.45    Good
1     244.0   54.0  220.0  307.58  0.90  0.58      129.73  Medium
2     196.0  187.0   17.0   56.98  0.84  0.42      170.31  Medium
3     187.0  129.0  122.0    6.46  0.32  0.61         NaN     NaN
4      98.0  177.0    0.0   86.78  1.00  0.35      133.20  Medium
...     ...    ...    ...     ...   ...   ...         ...     ...
5495    9.0   81.0  228.0  220.27  0.92  0.46       76.23    Good
5496   71.0   65.0  228.0  242.21  0.75  0.57       85.38    Good
5497   24.0  162.0  184.0  188.25  0.77  0.41      123.25    Good
5498  181.0  129.0  191.0  290.32  0.33  0.63         NaN     NaN
5499   61.0   86.0   56.0  110.00  0.21  0.28       75.11  Medium

[5500 rows x 8 columns]

In [698]:
df.isna().sum()

R               0
G               0
B               0
H               0
S               0
L               0
Brightness    773
Target        773
dtype: int64

In [699]:
#WE are recompiling the brighness value

def bright (R,G,B):
    return round(0.299*R+0.587*G+0.114*B,2)
df['Brightness']=df.apply(lambda row: bright(row['R'],row['G'],row['B']),axis=1)
    

In [700]:
df

R      G      B       H     S     L  Brightness  Target
0     110.0  185.0  219.0  198.72  0.60  0.65      166.45    Good
1     244.0   54.0  220.0  307.58  0.90  0.58      129.73  Medium
2     196.0  187.0   17.0   56.98  0.84  0.42      170.31  Medium
3     187.0  129.0  122.0    6.46  0.32  0.61      145.54     NaN
4      98.0  177.0    0.0   86.78  1.00  0.35      133.20  Medium
...     ...    ...    ...     ...   ...   ...         ...     ...
5495    9.0   81.0  228.0  220.27  0.92  0.46       76.23    Good
5496   71.0   65.0  228.0  242.21  0.75  0.57       85.38    Good
5497   24.0  162.0  184.0  188.25  0.77  0.41      123.25    Good
5498  181.0  129.0  191.0  290.32  0.33  0.63      151.62     NaN
5499   61.0   86.0   56.0  110.00  0.21  0.28       75.11  Medium

[5500 rows x 8 columns]

In [701]:
df.isna().sum()

R               0
G               0
B               0
H               0
S               0
L               0
Brightness      0
Target        773
dtype: int64

In [702]:
df.dropna(subset=['Target'],inplace=True)
df=df.reset_index(drop=True)

In [703]:
df

R      G      B       H     S     L  Brightness  Target
0     110.0  185.0  219.0  198.72  0.60  0.65      166.45    Good
1     244.0   54.0  220.0  307.58  0.90  0.58      129.73  Medium
2     196.0  187.0   17.0   56.98  0.84  0.42      170.31  Medium
3      98.0  177.0    0.0   86.78  1.00  0.35      133.20  Medium
4      22.0  177.0   94.0  147.87  0.78  0.39      121.19  Medium
...     ...    ...    ...     ...   ...   ...         ...     ...
4722  127.0   13.0  185.0  279.77  0.87  0.39       66.69  Medium
4723    9.0   81.0  228.0  220.27  0.92  0.46       76.23    Good
4724   71.0   65.0  228.0  242.21  0.75  0.57       85.38    Good
4725   24.0  162.0  184.0  188.25  0.77  0.41      123.25    Good
4726   61.0   86.0   56.0  110.00  0.21  0.28       75.11  Medium

[4727 rows x 8 columns]

In [704]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Medium    2607
Good      1376
Bad        744
Name: count, dtype: int64

In [705]:
df.isna().sum()

R             0
G             0
B             0
H             0
S             0
L             0
Brightness    0
Target        0
dtype: int64

In [706]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Medium    2607
Good      1376
Bad        744
Name: count, dtype: int64

In [707]:
#Seperating input and output features

x=df.iloc[:,:-1]
x

R      G      B       H     S     L  Brightness
0     110.0  185.0  219.0  198.72  0.60  0.65      166.45
1     244.0   54.0  220.0  307.58  0.90  0.58      129.73
2     196.0  187.0   17.0   56.98  0.84  0.42      170.31
3      98.0  177.0    0.0   86.78  1.00  0.35      133.20
4      22.0  177.0   94.0  147.87  0.78  0.39      121.19
...     ...    ...    ...     ...   ...   ...         ...
4722  127.0   13.0  185.0  279.77  0.87  0.39       66.69
4723    9.0   81.0  228.0  220.27  0.92  0.46       76.23
4724   71.0   65.0  228.0  242.21  0.75  0.57       85.38
4725   24.0  162.0  184.0  188.25  0.77  0.41      123.25
4726   61.0   86.0   56.0  110.00  0.21  0.28       75.11

[4727 rows x 7 columns]

In [708]:
y=df.iloc[:,-1]
y

0         Good
1       Medium
2       Medium
3       Medium
4       Medium
         ...  
4722    Medium
4723      Good
4724      Good
4725      Good
4726    Medium
Name: Target, Length: 4727, dtype: object

In [709]:
#Now lets do train test split on various classification algorithms
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.7,random_state=42,stratify=y)
# stratify function is added for better prediction and distribution of the labels
xtrain
xtest
ytrain
ytest

983     Medium
2075    Medium
2947    Medium
1859    Medium
1470    Medium
         ...  
3802    Medium
2595    Medium
319       Good
2505    Medium
4641    Medium
Name: Target, Length: 1419, dtype: object

In [710]:
# #Scaling done to make the values lie in a similar point
# from sklearn.preprocessing import MinMaxScaler
# scaler=MinMaxScaler()
# scaler.fit(xtrain)
# xtrain=scaler.transform(xtrain)
# xtest=scaler.transform(xtest)

In [711]:
# Stdscaler
# from sklearn.preprocessing import StandardScaler
# scaler=StandardScaler()
# scaler.fit(xtrain)
# xtrain=scaler.transform(xtrain)
# xtest=scaler.transform(xtest)

In [712]:
#Building and testing various models

#KNN

# from sklearn.neighbors import KNeighborsClassifier
# knnmodel=KNeighborsClassifier()
# knnmodel.fit(xtrain,ytrain)
# ypred=knnmodel.predict(xtest)
# ypred

In [713]:
# print(knnmodel.predict(scaler.transform([[255,192,203,350.0,1.0,0.888,204.93]])))

In [714]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [715]:
# ypred=knnmodel.predict(xtest)
# print('Accuracy:',round(accuracy_score(ytest,ypred),4))
# print('Classification Report:',(classification_report(ytest,ypred)))
# print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

In [716]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtreemodel=DecisionTreeClassifier(max_depth=6,min_samples_split=20,min_samples_leaf=10,random_state=42)
dtreemodel.fit(xtrain,ytrain)
ypred=dtreemodel.predict(xtest)
ypred

array(['Medium', 'Medium', 'Medium', ..., 'Good', 'Medium', 'Medium'],
      shape=(1419,), dtype=object)

In [717]:
print(dtreemodel.predict([[255,192,203,350.0,1.0,0.888,204.93]]))

['Good']


c:\Users\leepa\Documents\color_mood_predictor_ml\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [718]:
ypred=dtreemodel.predict(xtest)
print('Accuracy:',round(accuracy_score(ytest,ypred),4))
print('Classification Report:',(classification_report(ytest,ypred)))
print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

Accuracy: 0.9549
Classification Report:               precision    recall  f1-score   support

         Bad       0.99      0.98      0.98       223
        Good       0.99      0.86      0.92       413
      Medium       0.93      1.00      0.96       783

    accuracy                           0.95      1419
   macro avg       0.97      0.95      0.96      1419
weighted avg       0.96      0.95      0.95      1419

COnfusion Matrix: [[218   3   2]
 [  1 356  56]
 [  2   0 781]]


In [719]:
# # 1️⃣ RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier

rfmodel = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_split=20,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)
rfmodel.fit(xtrain, ytrain)
ypred= rfmodel.predict(xtest)
ypred


# 2️⃣ GRADIENT BOOSTING
from sklearn.ensemble import GradientBoostingClassifier

gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)
gb_model.fit(xtrain, ytrain)
ypred= gb_model.predict(xtest)
ypred


# 3️⃣ SVM (requires scaling)
# from sklearn.svm import SVC
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# xtrain_scaled = scaler.fit_transform(xtrain)
# xtest_scaled = scaler.transform(xtest)

# svm_model = SVC(
#     kernel='rbf',
#     C=10,
#     gamma='scale',
#     probability=True,
#     random_state=42
# )
# svm_model.fit(xtrain, ytrain)
# ypred= svm_model.predict(xtest)
# ypred
# from sklearn.svm import SVC
# svmmodel=SVC()
# svmmodel.fit(xtrain,ytrain)
# ypred=svmmodel.predict(xtest)
# ypred

array(['Medium', 'Medium', 'Medium', ..., 'Good', 'Medium', 'Medium'],
      shape=(1419,), dtype=object)

In [720]:
print(rfmodel.predict([[255,192,203,350.0,1.0,0.888,204.93]]))

['Good']


c:\Users\leepa\Documents\color_mood_predictor_ml\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [721]:
ypred=rfmodel.predict(xtest)
print('Accuracy:',round(accuracy_score(ytest,ypred),4))
print('Classification Report:',(classification_report(ytest,ypred)))
print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

Accuracy: 0.9922
Classification Report:               precision    recall  f1-score   support

         Bad       0.99      0.99      0.99       223
        Good       1.00      0.99      0.99       413
      Medium       0.99      0.99      0.99       783

    accuracy                           0.99      1419
   macro avg       0.99      0.99      0.99      1419
weighted avg       0.99      0.99      0.99      1419

COnfusion Matrix: [[221   0   2]
 [  0 408   5]
 [  3   1 779]]


In [722]:
print(gb_model.predict([[255,192,203,350.0,1.0,0.888,204.93]]))

['Good']


c:\Users\leepa\Documents\color_mood_predictor_ml\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


In [723]:
ypred=gb_model.predict(xtest)
print('Accuracy:',round(accuracy_score(ytest,ypred),4))
print('Classification Report:',(classification_report(ytest,ypred)))
print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

Accuracy: 0.9986
Classification Report:               precision    recall  f1-score   support

         Bad       1.00      1.00      1.00       223
        Good       1.00      1.00      1.00       413
      Medium       1.00      1.00      1.00       783

    accuracy                           1.00      1419
   macro avg       1.00      1.00      1.00      1419
weighted avg       1.00      1.00      1.00      1419

COnfusion Matrix: [[223   0   0]
 [  0 411   2]
 [  0   0 783]]


In [724]:
# print(svmmodel.predict(scaler.transform([[0,0,0,240,100,50,29]])))

In [725]:
# import numpy as np

# test_inputs = np.array([
#     [255, 0, 0, 0, 100, 50, 76],        # Bright Red → Bad
#     [0, 255, 0, 120, 100, 50, 150],     # Bright Green → Good
#     [0, 0, 255, 240, 100, 50, 29],      # Bright Blue → Medium
#     [255, 255, 0, 60, 100, 50, 178],    # Yellow → Good/Medium
#     [128, 128, 128, 0, 0, 50, 128]      # Grey → Medium
# ], dtype=float)

# test_inputs_scaled = scaler.transform(test_inputs)
# y_pred_test = svmmodel.predict(test_inputs_scaled)

# print(y_pred_test)

In [726]:
# ypred=svmmodel.predict(xtest)
# print('Accuracy:',round(accuracy_score(ytest,ypred),4))
# print('Classification Report:',(classification_report(ytest,ypred)))
# print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

In [727]:
# print(svmmodel.classes_)

In [ ]:
# install catboost if missing (magic command for Jupyter)
%pip install -q catboost

from catboost import CatBoostClassifier

cb_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=4,
    l2_leaf_reg=3,
    random_seed=42,
    verbose=100
)

cb_model.fit(xtrain, ytrain)
ypred = cb_model.predict(xtest)