In [687]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv(r'C:\Users\leepa\Documents\color_mood_predictor_ml\data\color_perception.csv')
df

R           G           B           H          S          L  \
0       23.847430   23.448821   30.763561  254.906128        NaN  18.299849   
1        0.000000    0.000000    0.000000  188.912315  24.247746  20.811066   
2       20.671853   21.062483    6.699714  282.663346   7.280729  15.296322   
3        9.433904    8.585722   24.062659   35.161961  12.855861  14.810364   
4       45.172789   42.933563   49.121557  238.508022  11.003812   3.050956   
...           ...         ...         ...         ...        ...        ...   
11995  148.998804  158.320180  158.692707         NaN  53.446353  57.368169   
11996  179.074019  173.554068  151.102362   65.427855  55.737503  48.853482   
11997  128.678951  113.564700  123.339969  255.945910  51.582686  65.486222   
11998  166.962251  147.450931  160.670196  244.251582  48.444865  45.535797   
11999  115.839357  108.863862  119.206796  242.461031  65.908545  59.172003   

       Brightness Target  
0       26.217808    Bad  
1        1.440915    Bad  
2       30.236151    Bad  
3       13.977165    Bad  
4       47.896312    Bad  
...           ...    ...  
11995  153.018218   Good  
11996  166.464116   Good  
11997  124.814628   Good  
11998  161.583879   Good  
11999  124.338248   Good  

[12000 rows x 8 columns]

In [688]:
df.head(10)

R          G          B           H          S          L  \
0  23.847430  23.448821  30.763561  254.906128        NaN  18.299849   
1   0.000000   0.000000   0.000000  188.912315  24.247746  20.811066   
2  20.671853  21.062483   6.699714  282.663346   7.280729  15.296322   
3   9.433904   8.585722  24.062659   35.161961  12.855861  14.810364   
4  45.172789  42.933563  49.121557  238.508022  11.003812   3.050956   
5  31.730577  12.822113   7.080025   97.685651  13.001701  13.667757   
6        NaN  58.180092  61.236349  262.442580   8.918833   7.023363   
7  57.444628  44.670837  42.344325  117.065996   1.851116   8.961643   
8  45.125246  55.612918  53.839238  202.059791  15.938937  22.180319   
9  51.365870  37.787006  62.399427  183.085449        NaN  13.068321   

   Brightness Target  
0   26.217808    Bad  
1    1.440915    Bad  
2   30.236151    Bad  
3   13.977165    Bad  
4   47.896312    Bad  
5   21.819775    Bad  
6   58.011626    Bad  
7   53.988924    Bad  
8   51.072432    Bad  
9   53.967703    Bad

In [689]:
df.tail(10)

R           G           B           H          S          L  \
11990  166.554743  172.997635  165.503920  238.628969  60.681193  63.386926   
11991  115.787313  123.638478  106.277070  258.169566  59.982225  48.621542   
11992  188.858299  202.164963  205.391303  159.389090  53.541507  55.565462   
11993  169.891034  183.383000  171.953655  180.229456  50.499142  63.384817   
11994  184.561815  182.612569  198.315700  159.592839  59.832989  56.624979   
11995  148.998804  158.320180  158.692707         NaN  53.446353  57.368169   
11996  179.074019  173.554068  151.102362   65.427855  55.737503  48.853482   
11997  128.678951  113.564700  123.339969  255.945910  51.582686  65.486222   
11998  166.962251  147.450931  160.670196  244.251582  48.444865  45.535797   
11999  115.839357  108.863862  119.206796  242.461031  65.908545  59.172003   

       Brightness Target  
11990  174.411607   Good  
11991  121.400721   Good  
11992  194.067158   Good  
11993  164.808116   Good  
11994  186.819095   Good  
11995  153.018218   Good  
11996  166.464116   Good  
11997  124.814628   Good  
11998  161.583879   Good  
11999  124.338248   Good

In [690]:
df.columns

Index(['R', 'G', 'B', 'H', 'S', 'L', 'Brightness', 'Target'], dtype='object')

In [691]:
df.size

96000

In [692]:
df.shape

(12000, 8)

In [693]:
df.dtypes

R             float64
G             float64
B             float64
H             float64
S             float64
L             float64
Brightness    float64
Target         object
dtype: object

In [694]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Bad       4000
Medium    4000
Good      4000
Name: count, dtype: int64

In [695]:
#Checking for Null values
df.isna().sum()

R             360
G             360
B             360
H             600
S             600
L             600
Brightness    480
Target          0
dtype: int64

In [696]:
#There are missing values so we need to fill it with 
#Either mean mode or median based on the scenario.
#When to use them accordingly??????????

#Mean: sum of all values divided by number of total values
#Median: It is the middle value
#Mode()[0]: It is the value which appears most
#We are using Median to to fill to avoid overfitting or underfitting
#we will fill RGB with median and then HSL values are derived from this

In [697]:
df=pd.read_csv(r'C:\Users\leepa\Documents\color_mood_predictor_ml\data\color_perception.csv')
for columns in ['R','G','B']:
    df[columns].fillna(df[columns].median(),inplace=True)

C:\Users\leepa\AppData\Local\Temp\ipykernel_5172\2974766677.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[columns].fillna(df[columns].median(),inplace=True)
C:\Users\leepa\AppData\Local\Temp\ipykernel_5172\2974766677.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For 

In [698]:
df

R           G           B           H          S          L  \
0       23.847430   23.448821   30.763561  254.906128        NaN  18.299849   
1        0.000000    0.000000    0.000000  188.912315  24.247746  20.811066   
2       20.671853   21.062483    6.699714  282.663346   7.280729  15.296322   
3        9.433904    8.585722   24.062659   35.161961  12.855861  14.810364   
4       45.172789   42.933563   49.121557  238.508022  11.003812   3.050956   
...           ...         ...         ...         ...        ...        ...   
11995  148.998804  158.320180  158.692707         NaN  53.446353  57.368169   
11996  179.074019  173.554068  151.102362   65.427855  55.737503  48.853482   
11997  128.678951  113.564700  123.339969  255.945910  51.582686  65.486222   
11998  166.962251  147.450931  160.670196  244.251582  48.444865  45.535797   
11999  115.839357  108.863862  119.206796  242.461031  65.908545  59.172003   

       Brightness Target  
0       26.217808    Bad  
1        1.440915    Bad  
2       30.236151    Bad  
3       13.977165    Bad  
4       47.896312    Bad  
...           ...    ...  
11995  153.018218   Good  
11996  166.464116   Good  
11997  124.814628   Good  
11998  161.583879   Good  
11999  124.338248   Good  

[12000 rows x 8 columns]

In [699]:
df.isna().sum()

R               0
G               0
B               0
H             600
S             600
L             600
Brightness    480
Target          0
dtype: int64

In [700]:
#here we are implenting a function for the hsl values
import colorsys 
def rgb_to_hsl(R,G,B):
    r,g,b=R/255,G/255,B/255
    h,l,s=colorsys.rgb_to_hls(r,g,b)
    return round(h*360,2),round(s,2),round (l,2)


In [701]:
#APPLY THE FUNCTION ROW WISE
df['H'],df['S'],df['L']=zip(*df.apply(lambda row: rgb_to_hsl(row['R'],row["G"],row["B"]),axis=1))
df

R           G           B       H     S     L  Brightness  \
0       23.847430   23.448821   30.763561  243.27  0.13  0.11   26.217808   
1        0.000000    0.000000    0.000000    0.00  0.00  0.00    1.440915   
2       20.671853   21.062483    6.699714   61.63  0.52  0.05   30.236151   
3        9.433904    8.585722   24.062659  243.29  0.47  0.06   13.977165   
4       45.172789   42.933563   49.121557  261.71  0.07  0.18   47.896312   
...           ...         ...         ...     ...   ...   ...         ...   
11995  148.998804  158.320180  158.692707  182.31  0.05  0.60  153.018218   
11996  179.074019  173.554068  151.102362   48.16  0.16  0.65  166.464116   
11997  128.678951  113.564700  123.339969  321.19  0.06  0.47  124.814628   
11998  166.962251  147.450931  160.670196  319.35  0.10  0.62  161.583879   
11999  115.839357  108.863862  119.206796  280.47  0.05  0.45  124.338248   

      Target  
0        Bad  
1        Bad  
2        Bad  
3        Bad  
4        Bad  
...      ...  
11995   Good  
11996   Good  
11997   Good  
11998   Good  
11999   Good  

[12000 rows x 8 columns]

In [702]:
df.isna().sum()

R               0
G               0
B               0
H               0
S               0
L               0
Brightness    480
Target          0
dtype: int64

In [703]:
#WE are recompiling the brighness value

def bright (R,G,B):
    return round(0.299*R+0.587*G+0.114*B,2)
df['Brightness']=df.apply(lambda row: bright(row['R'],row['G'],row['B']),axis=1)
    

In [704]:
df

R           G           B       H     S     L  Brightness  \
0       23.847430   23.448821   30.763561  243.27  0.13  0.11       24.40   
1        0.000000    0.000000    0.000000    0.00  0.00  0.00        0.00   
2       20.671853   21.062483    6.699714   61.63  0.52  0.05       19.31   
3        9.433904    8.585722   24.062659  243.29  0.47  0.06       10.60   
4       45.172789   42.933563   49.121557  261.71  0.07  0.18       44.31   
...           ...         ...         ...     ...   ...   ...         ...   
11995  148.998804  158.320180  158.692707  182.31  0.05  0.60      155.58   
11996  179.074019  173.554068  151.102362   48.16  0.16  0.65      172.65   
11997  128.678951  113.564700  123.339969  321.19  0.06  0.47      119.20   
11998  166.962251  147.450931  160.670196  319.35  0.10  0.62      154.79   
11999  115.839357  108.863862  119.206796  280.47  0.05  0.45      112.13   

      Target  
0        Bad  
1        Bad  
2        Bad  
3        Bad  
4        Bad  
...      ...  
11995   Good  
11996   Good  
11997   Good  
11998   Good  
11999   Good  

[12000 rows x 8 columns]

In [705]:
df.isna().sum()

R             0
G             0
B             0
H             0
S             0
L             0
Brightness    0
Target        0
dtype: int64

In [706]:
df.dropna(subset=['Target'],inplace=True)
df=df.reset_index(drop=True)

In [707]:
df

R           G           B       H     S     L  Brightness  \
0       23.847430   23.448821   30.763561  243.27  0.13  0.11       24.40   
1        0.000000    0.000000    0.000000    0.00  0.00  0.00        0.00   
2       20.671853   21.062483    6.699714   61.63  0.52  0.05       19.31   
3        9.433904    8.585722   24.062659  243.29  0.47  0.06       10.60   
4       45.172789   42.933563   49.121557  261.71  0.07  0.18       44.31   
...           ...         ...         ...     ...   ...   ...         ...   
11995  148.998804  158.320180  158.692707  182.31  0.05  0.60      155.58   
11996  179.074019  173.554068  151.102362   48.16  0.16  0.65      172.65   
11997  128.678951  113.564700  123.339969  321.19  0.06  0.47      119.20   
11998  166.962251  147.450931  160.670196  319.35  0.10  0.62      154.79   
11999  115.839357  108.863862  119.206796  280.47  0.05  0.45      112.13   

      Target  
0        Bad  
1        Bad  
2        Bad  
3        Bad  
4        Bad  
...      ...  
11995   Good  
11996   Good  
11997   Good  
11998   Good  
11999   Good  

[12000 rows x 8 columns]

In [708]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Bad       4000
Medium    4000
Good      4000
Name: count, dtype: int64

In [709]:
df.isna().sum()

R             0
G             0
B             0
H             0
S             0
L             0
Brightness    0
Target        0
dtype: int64

In [710]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Bad       4000
Medium    4000
Good      4000
Name: count, dtype: int64

In [711]:
#Seperating input and output features

x=df.iloc[:,:-1]
x

R           G           B       H     S     L  Brightness
0       23.847430   23.448821   30.763561  243.27  0.13  0.11       24.40
1        0.000000    0.000000    0.000000    0.00  0.00  0.00        0.00
2       20.671853   21.062483    6.699714   61.63  0.52  0.05       19.31
3        9.433904    8.585722   24.062659  243.29  0.47  0.06       10.60
4       45.172789   42.933563   49.121557  261.71  0.07  0.18       44.31
...           ...         ...         ...     ...   ...   ...         ...
11995  148.998804  158.320180  158.692707  182.31  0.05  0.60      155.58
11996  179.074019  173.554068  151.102362   48.16  0.16  0.65      172.65
11997  128.678951  113.564700  123.339969  321.19  0.06  0.47      119.20
11998  166.962251  147.450931  160.670196  319.35  0.10  0.62      154.79
11999  115.839357  108.863862  119.206796  280.47  0.05  0.45      112.13

[12000 rows x 7 columns]

In [712]:
y=df.iloc[:,-1]
y

0         Bad
1         Bad
2         Bad
3         Bad
4         Bad
         ... 
11995    Good
11996    Good
11997    Good
11998    Good
11999    Good
Name: Target, Length: 12000, dtype: object

In [713]:
#Now lets do train test split on various classification algorithms
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.7,random_state=42,stratify=y)
# stratify function is added for better prediction and distribution of the labels
xtrain
xtest
ytrain
ytest

1496        Bad
6636     Medium
11488      Good
11264      Good
9091       Good
          ...  
10787      Good
3184        Bad
1892        Bad
2489        Bad
10527      Good
Name: Target, Length: 3600, dtype: object

In [714]:
#Fetching the Output counts
df['Target'].value_counts()

Target
Bad       4000
Medium    4000
Good      4000
Name: count, dtype: int64

In [715]:
# #Scaling done to make the values lie in a similar point
# from sklearn.preprocessing import MinMaxScaler
# scaler=MinMaxScaler()
# scaler.fit(xtrain)
# xtrain=scaler.transform(xtrain)
# xtest=scaler.transform(xtest)

In [716]:
# Stdscaler
# from sklearn.preprocessing import StandardScaler
# scaler=StandardScaler()
# scaler.fit(xtrain)
# xtrain=scaler.transform(xtrain)
# xtest=scaler.transform(xtest)

In [717]:
#Building and testing various models

#KNN

# from sklearn.neighbors import KNeighborsClassifier
# knnmodel=KNeighborsClassifier()
# knnmodel.fit(xtrain,ytrain)
# ypred=knnmodel.predict(xtest)
# ypred

In [718]:
# print(knnmodel.predict(scaler.transform([[255,192,203,350.0,1.0,0.888,204.93]])))

In [719]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [720]:
# ypred=knnmodel.predict(xtest)
# print('Accuracy:',round(accuracy_score(ytest,ypred),4))
# print('Classification Report:',(classification_report(ytest,ypred)))
# print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

In [721]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtreemodel=DecisionTreeClassifier(max_depth=6,min_samples_split=20,min_samples_leaf=10,random_state=42)
dtreemodel.fit(xtrain,ytrain)
ypred=dtreemodel.predict(xtest)
ypred

array(['Bad', 'Medium', 'Good', ..., 'Bad', 'Bad', 'Medium'],
      shape=(3600,), dtype=object)

In [722]:
print(dtreemodel.predict([[150,200,170,150,55,60,180]]))

['Good']


c:\Users\leepa\Documents\color_mood_predictor_ml\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [723]:
ypred=dtreemodel.predict(xtest)
print('Accuracy:',round(accuracy_score(ytest,ypred),4))
print('Classification Report:',(classification_report(ytest,ypred)))
print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

Accuracy: 0.9286
Classification Report:               precision    recall  f1-score   support

         Bad       0.96      0.93      0.94      1200
        Good       0.96      0.93      0.95      1200
      Medium       0.87      0.92      0.90      1200

    accuracy                           0.93      3600
   macro avg       0.93      0.93      0.93      3600
weighted avg       0.93      0.93      0.93      3600

COnfusion Matrix: [[1120    0   80]
 [   0 1121   79]
 [  51   47 1102]]


In [728]:
print(dtreemodel.predict([[90, 95, 100, 30, 30, 40, 94]]))  # Medium examples
# [90, 95, 100, 30, 30, 40, 94]
# [110, 105, 100, 25, 35, 45, 106]
# [100, 110, 120, 210, 40, 48, 108]
# [85, 90, 95, 60, 28, 35, 88]


['Good']


c:\Users\leepa\Documents\color_mood_predictor_ml\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [725]:
# # 1️⃣ RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier
rfmodel = RandomForestClassifier(n_estimators=300,max_depth=6,min_samples_split=20,min_samples_leaf=10,random_state=42,
    n_jobs=-1)
rfmodel.fit(xtrain, ytrain)
ypred= rfmodel.predict(xtest)
ypred

array(['Bad', 'Medium', 'Good', ..., 'Bad', 'Bad', 'Medium'],
      shape=(3600,), dtype=object)

In [726]:
ypred=rfmodel.predict(xtest)
print('Accuracy:',round(accuracy_score(ytest,ypred),4))
print('Classification Report:',(classification_report(ytest,ypred)))
print('COnfusion Matrix:',(confusion_matrix(ytest,ypred)))

Accuracy: 0.9308
Classification Report:               precision    recall  f1-score   support

         Bad       0.96      0.94      0.95      1200
        Good       0.96      0.94      0.95      1200
      Medium       0.88      0.92      0.90      1200

    accuracy                           0.93      3600
   macro avg       0.93      0.93      0.93      3600
weighted avg       0.93      0.93      0.93      3600

COnfusion Matrix: [[1130    0   70]
 [   0 1123   77]
 [  53   49 1098]]


In [727]:
print(rfmodel.classes_)

['Bad' 'Good' 'Medium']
